In [1]:
import numpy as np
import pandas as pd

In [4]:
Attributs = np.array([[1,7,3],
                     [1/7,1,1/3],
                     [1/3,3,1]])
eigenvalues, eigenvectors = np.linalg.eig(Attributs)


real_mask = np.isreal(eigenvalues)
real_eigenvalues = eigenvalues[real_mask].real
real_eigenvectors = eigenvectors[:, real_mask].real


max_idx = np.argmax(real_eigenvalues)

biggest_eigenvalue = real_eigenvalues[max_idx]
corresponding_eigenvector = real_eigenvectors[:, max_idx]

print("Biggest Eigenvalue:", biggest_eigenvalue)
print("Corresponding Eigenvector:", corresponding_eigenvector) 



A1 = np.array([[1, 7],
               [0.143, 1]])
A2 = np.array([[1, 0.2],
               [5, 1]])
A3 = np.array([[1, 0.111],
               [9, 1]])



Biggest Eigenvalue: 3.007021765129934
Corresponding Eigenvector: [0.93305777 0.12258265 0.33819624]


In [15]:
import numpy as np

A = np.array([[30, 0.1, 1, 20],
              [100, 0.7, 1, 40],
              [50, 1, 2, 10],
              [300, 2, 3, 35]], dtype=float) # Force float to prevent integer truncation

for i in range(A.shape[1]):
    col_min = np.min(A[:, i])
    col_max = np.max(A[:, i])
    
    if i == 2:
        A[:, i] = (A[:, i] - col_min) / (col_max - col_min)
    else:
        A[:, i] = (col_max - A[:, i]) / (col_max - col_min)

columns_std = np.std(A, axis=0)
print("Standard deviation attribute:\n", columns_std)



print("\nNormalized Matrix:\n", A)

corr_matrix = np.corrcoef(A, rowvar=False)
print("\nCorrelation Matrix:\n", corr_matrix)

C = np.zeros(A.shape[1])
for j in range(A.shape[1]):
    conflict_sum = np.sum(1 - corr_matrix[j, :])
    C[j] = columns_std[j] * conflict_sum

print("\nConflict Coefficients:\n", C)



Standard deviation attribute:
 [0.3963136  0.36178229 0.4145781  0.39747467]

Normalized Matrix:
 [[1.         1.         0.         0.66666667]
 [0.74074074 0.68421053 0.         0.        ]
 [0.92592593 0.52631579 0.5        1.        ]
 [0.         0.         1.         0.16666667]]

Correlation Matrix:
 [[ 1.          0.90750206 -0.81714459  0.5877976 ]
 [ 0.90750206  1.         -0.9430641   0.31263116]
 [-0.81714459 -0.9430641   1.         -0.03160698]
 [ 0.5877976   0.31263116 -0.03160698  1.        ]]

Conflict Coefficients:
 [0.92017873 0.98510817 1.98658183 0.84708935]


In [18]:
SWM = np.array([[0.035, 847, 0.335, 1.76, 0.59],
                [0.027, 834, 0.335, 1.68, 0.665],
                [0.037, 808, 0.59, 2.4, 0.5],
                [0.028, 821, 0.5, 1.59, 0.41]])

best_ideal = np.array([])
for i in range(5):
    best_ideal = np.append(best_ideal, np.max(SWM[:, i]))

print("Best ideal values:", best_ideal)

norm_SWM = np.zeros(SWM.shape)
for i in range(SWM.shape[1]):
    col_min = np.min(SWM[:, i])
    col_max = np.max(SWM[:, i])
    
    if i == 2 or i == 4:
        norm_SWM[:, i] = SWM[:, i]  / best_ideal[i]
    else:
        norm_SWM[:, i] = best_ideal[i] / SWM[:, i]

print("\nNormalized SWM:\n", norm_SWM)


poids = np.array([0.331, 0.181, 0.369, 0.072, 0.047])

result = norm_SWM @ poids
print("\nFinal Result:\n", result)


Best ideal values: [3.70e-02 8.47e+02 5.90e-01 2.40e+00 6.65e-01]

Normalized SWM:
 [[1.05714286 1.         0.56779661 1.36363636 0.88721805]
 [1.37037037 1.01558753 0.56779661 1.42857143 1.        ]
 [1.         1.04826733 1.         1.         0.7518797 ]
 [1.32142857 1.0316687  0.84745763 1.50943396 0.61654135]]

Final Result:
 [0.8803123  0.99678803 0.99707473 1.07449344]
